# Site settings
title: Latest Blogs &mdash; Olympia Academia
description: "Olympia Academia, amu science society, boolean autocrats, amu, aligarh muslim university, amu club, amu coders"
url: "https://olympiaacademia.github.io/blogs/"
ogimage: "https://olympiaacademia.github.io/apple-touch-icon.png"
author:
  name: "Olympia Academia"
  email: "olymp.acad@gmail.com"
  url: "https://olympiaacademia.github.io"


# Build settings
baseurl: /blogs # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
